title: MUSA 500 Assignment 6
logo: /assets/img/logo.png
description: Tweets About Eviction Around the World
show_downloads: false
repository: bri-ne/MUSA500_Assignment6
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
